# Generated by Django 3.1.1 on 2020-09-15 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField(max_length=500, verbose_name='Description')),
                ('img', models.ImageField(upload_to='product_img/', verbose_name='Image')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
